[metadata]
name    = "sync"
author  = "hacdias"

[global]
plan    = "example"
case    = "sync"
builder = "docker:go"
runner  = "cluster:k8s"
total_instances = 150

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="http://localhost:8081"
  registry_type="aws"

[[groups]]
id = "first"
instances = { count = 150 }

