apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: testground-sync-service
spec:
  selector:
    matchLabels:
      name: testground-sync-service
  template:
    metadata:
      labels:
        name: testground-sync-service
    spec:
      terminationGracePeriodSeconds: 10
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: testground-sync-service
          image: iptestground/sync-service:latest
          command: ["/service"]
          ports:
            - name: sidecarhttp
              containerPort: 6060
          resources:
            limits:
              cpu: 20m
              memory: 26Mi
            requests:
              cpu: 20m
              memory: 26Mi
      nodeSelector:
        testground.node.role.plan: "true"
